### ISSUE TITLE
error 60: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by Stevemoretz** [ctwillie/expo-server-sdk-php#14]
Currently getting : 

```
GuzzleHttp\Exception\RequestException : cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://exp.host/--/api/v2/push/send
```

using the basic example from docs, looks like some problem for expo.

using :

- php 7.4
- Latest version of your library

I'll provide a PR to fix this.

**Comment by ctwillie** [comment]
Thanks for using this package! 

I don't have extensive knowledge on curl/ssl verification, so not exactly sure why it failed. I looked into the Expo servers ssl certificate and saw it is still valid for about 15 days from now.  Maybe try ensure your CA bundle is update to date on your server.

But with that said, the PR you provided cannot be merged as it is an insecure default to bypass ssl verification.  If you choose to disable verification, WHICH I DO NOT RECOMMEND, you can do the below:

```php
// THIS IS NOT RECOMMENDED FOR PRODUCTION ENVIRONMENTS

// if you are using the file driver
$expo = new Expo('file', ['verify' => false]);

// if you are not using the file driver
$expo = new Expo(null, ['verify' => false]);
```

**Comment by Stevemoretz** [comment]
> Thanks for using this package!
> 
> I don't have extensive knowledge on curl/ssl verification, so not exactly sure why it failed. I looked into the Expo servers ssl certificate and saw it is still valid for about 15 days from now. Maybe try ensuring your CA bundle is up to date on your server.
> 
> But with that said, the PR you provided cannot be merged as it is an insecure default to bypass ssl verification. If you choose to disable verification, WHICH I DO NOT RECOMMEND, you can do the below:
> 
> ```
> // THIS IS NOT RECOMMENDED FOR PRODUCTION ENVIRONMENTS
> 
> // if you are using the file driver
> $expo = new Expo('file', ['verify' => false]);
> 
> // if you are not using the file driver
> $expo = new Expo(null, ['verify' => false]);
> ```

OH I didn't see that option, no the expo server shows valid certificate but you get the errors sometimes, this is a common issue.
