### ISSUE TITLE
categoryIdentifier not received

### ISSUE THREAD

**Issue by raonikhil** [ctwillie/expo-server-sdk-php#23]
I am sending this data via the SDK. I receive everything except for the categoryId as categoryIdentifier. Is there anything that I am doing wrong?

```
$messages = [
     'title'      => $notification['title'],
     'body'       => $notification['body'],
     'to'         => $notification['device_token'],
     'data'       => json_decode($notification['json_data'], true),
     'categoryId' => $notification['category_identifier'],
];
```

I even tried sending categoryIdentifier and category_identifier but again was not able to consume it in react native.

**Comment by cedrictwillie** [comment]
Sorry for the late response. But I believe this is a question for the Expo team to answer. We are sending the category Id, for each message, from this sdk to the Expo servers. So, something may be going on between their servers and how you are handling their push event. Sorry, I know this doesn't help much.

**Comment by cedrictwillie** [comment]
@raonikhil Any update on this before I close this issue?

**Comment by raonikhil** [comment]
the index name should be `categoryId`, correct?

**Comment by ctwillie** [comment]
Yes, that is correct.

**Comment by raonikhil** [comment]
ok, i've not contacted expo but you can close this if you are saying you are sending the categoryId from your side
