### ISSUE TITLE
Bad data for ExpoException class constructor

### ISSUE THREAD

**Issue by mohierf** [ctwillie/expo-server-sdk-php#34]
When I tried to send more than 100 message in one operation my application raised this exception:
```
Exception: Wrong parameters for ExpoSDK\Exceptions\ExpoException([string $message [, long $code [, Throwable $previous = NULL]]]) /app/vendor/ctwillie/expo-server-sdk-php/src/ExpoErrorManager.php 59

```

After more investigation I found out that the problem is due to no error code in the Expo response. Removing the 2nd argument on the line 59, the application now raised a more interesting log:
```
ExpoException: You can send a maximum of 100 notifications per request (received 115); divide your requests.

```

**Comment by ctwillie** [comment]
Hey @mohierf ! Expo only allows 100 push notifications at a time [according to the docs](https://docs.expo.dev/push-notifications/sending-notifications/#request-errors:~:text=PUSH_TOO_MANY_NOTIFICATIONS,in%20each%20request.), so the second exception is expected.

But if no error code was in the response, we may need to have a default status code (500 maybe) to prevent the "wrong parameters" exception.

Feel free to PR if you are up for it!

**Comment by mohierf** [comment]
Thank you for your answer. I jsut saw that I was not using the most recent version of your package ... my bad! I am going to test the 2.0 version and, if needed, I will propose a PR.

**Comment by ctwillie** [comment]
Ok, sounds good. Hopefully this is resolved for you in the latest release! Let me know.

P.S. ..  don't forget to chunk your notifications to 100 before sending. This package does not chunk for you... which is another small feature that can be added at some point.

**Comment by devouted** [comment]
Hi @ctwillie @mohierf 
There is also one opened PR for additional ExpoException added few weeks ago, please review:
https://github.com/ctwillie/expo-server-sdk-php/pull/32

regards
